### ISSUE TITLE
The entropic index of Tsallis loss

### ISSUE THREAD

**Issue by zzzzzero** [Liuhong99/CST#1]
Hello, thanks for sharing your great work with codes!
But I  wonder why the entropic index seems to be a constant in the codes，while it can be updated in the paper。

**Comment by Ree1s** [comment]
> Hello, thanks for sharing your great work with codes! But I wonder why the entropic index seems to be a constant in the codes，while it can be updated in the paper。

Hello, I think it may be found in the B.3 Selection of alpha in this paper. The author said it is costly so he chose to discretize the region. By the way, I want to ask a question about the target classifier. Could you tell me why the ImageClassifer in the code has only one head but in the paper there are target classifier and source classifier? Thanks a lot!
